/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KittyInterface__factory } from "./KittyInterface__factory";
export { ZombieFeeding__factory } from "./ZombieFeeding__factory";
