/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zombieFactoryFromL1Sol from "./ZombieFactoryFromL1.sol";
export type { zombieFactoryFromL1Sol };
